sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - ES_VERSION="7.1.1"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}-amd64.deb
  - sudo service elasticsearch restart
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source
  - sleep 10
  - curl -X GET http://127.0.0.1:9200

script:
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
